"""initial

Revision ID: a1a8bc64dc2e
Revises:
Create Date: 2026-06-24 10:31:06.165476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a1a8bc64dc2e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("oauth_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("oauth_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feeds",
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subtitle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("http_etag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "http_last_modified", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("data_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stale", sa.Integer(), nullable=False),
        sa.Column("updates_enabled", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.Column("last_exception", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("url"),
    )
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published", sa.DateTime(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("enclosures", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("original_feed", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_hash_changed", sa.Integer(), nullable=True),
        sa.Column("read", sa.Integer(), nullable=False),
        sa.Column("read_modified", sa.DateTime(), nullable=True),
        sa.Column("important", sa.Integer(), nullable=False),
        sa.Column("important_modified", sa.DateTime(), nullable=True),
        sa.Column("added_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("first_updated", sa.DateTime(), nullable=False),
        sa.Column("first_updated_epoch", sa.DateTime(), nullable=False),
        sa.Column("feed_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed"],
            ["feeds.url"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feed_metadata",
        sa.Column("feed", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed"],
            ["feeds.url"],
        ),
        sa.PrimaryKeyConstraint("feed", "key"),
    )
    op.create_table(
        "entry_tags",
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("entry_id", "tag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_tags")
    op.drop_table("feed_metadata")
    op.drop_table("entries")
    op.drop_table("feeds")
    op.drop_table("categories")
    op.drop_table("users")
    # ### end Alembic commands ###
