"""adiciona-auto-cleanup-days-remove-feed-metadata

Revision ID: e8ce7b723866
Revises: f8979a38e1d0
Create Date: 2026-07-12 12:13:02.565777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e8ce7b723866"
down_revision: Union[str, Sequence[str], None] = "f8979a38e1d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feed_metadata")
    op.add_column("users", sa.Column("auto_cleanup_days", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auto_cleanup_days")
    op.create_table(
        "feed_metadata",
        sa.Column("feed", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["feed"], ["feeds.url"], name=op.f("feed_metadata_feed_fkey")
        ),
        sa.PrimaryKeyConstraint("feed", "key", name=op.f("feed_metadata_pkey")),
    )
    # ### end Alembic commands ###
