"""add-theme-and-font-to-users

Revision ID: f8979a38e1d0
Revises: eb14f9ff4729
Create Date: 2026-07-12 10:40:33.420315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f8979a38e1d0"
down_revision: Union[str, Sequence[str], None] = "eb14f9ff4729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_entries_search_vector"), table_name="entries", postgresql_using="gin"
    )
    op.drop_index(op.f("idx_entries_user_published"), table_name="entries")
    op.drop_column("entries", "search_vector")
    op.add_column(
        "users",
        sa.Column("theme_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("users", sa.Column("font_scale", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "font_scale")
    op.drop_column("users", "theme_mode")
    op.add_column(
        "entries",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple'::regconfig, regexp_replace((((((COALESCE(title, ''::character varying))::text || ' '::text) || (COALESCE(summary, ''::character varying))::text) || ' '::text) || (COALESCE(content, ''::character varying))::text), '<[^>]+>'::text, ''::text, 'g'::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("idx_entries_user_published"),
        "entries",
        ["user_id", sa.literal_column("published DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_entries_search_vector"),
        "entries",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
